/*!Peripheral access API for CXD5602 microcontrollers (generated using svd2rust v0.37.1 ( ))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 3;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
///Common register and bit access and modify traits
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn CRG();
    fn UART1();
    fn SPI3();
    fn I2C0();
    fn I2C1();
    fn EXDEVICE_0();
    fn EXDEVICE_1();
    fn EXDEVICE_2();
    fn EXDEVICE_3();
    fn EXDEVICE_4();
    fn EXDEVICE_5();
    fn EXDEVICE_6();
    fn EXDEVICE_7();
    fn EXDEVICE_8();
    fn EXDEVICE_9();
    fn EXDEVICE_10();
    fn EXDEVICE_11();
    fn SPI0();
    fn FIFO_TO();
    fn FIFO_FROM();
    fn SPH0();
    fn SPH1();
    fn SPH2();
    fn SPH3();
    fn SPH4();
    fn SPH5();
    fn SPH6();
    fn SPH7();
    fn SPH8();
    fn SPH9();
    fn SPH10();
    fn SPH11();
    fn SPH12();
    fn SPH13();
    fn SPH14();
    fn SPH15();
    fn TIMER0();
    fn TIMER1();
    fn GE2D();
    fn ROT();
    fn CISIF();
    fn SPI5();
    fn DMAC3();
    fn UART2();
    fn SPI4();
    fn DMAC1();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 119] = [
    Vector { _reserved: 0 },
    Vector { _handler: CRG },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _reserved: 0 },
    Vector {
        _handler: EXDEVICE_0,
    },
    Vector {
        _handler: EXDEVICE_1,
    },
    Vector {
        _handler: EXDEVICE_2,
    },
    Vector {
        _handler: EXDEVICE_3,
    },
    Vector {
        _handler: EXDEVICE_4,
    },
    Vector {
        _handler: EXDEVICE_5,
    },
    Vector {
        _handler: EXDEVICE_6,
    },
    Vector {
        _handler: EXDEVICE_7,
    },
    Vector {
        _handler: EXDEVICE_8,
    },
    Vector {
        _handler: EXDEVICE_9,
    },
    Vector {
        _handler: EXDEVICE_10,
    },
    Vector {
        _handler: EXDEVICE_11,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: FIFO_TO },
    Vector {
        _handler: FIFO_FROM,
    },
    Vector { _handler: SPH0 },
    Vector { _handler: SPH1 },
    Vector { _handler: SPH2 },
    Vector { _handler: SPH3 },
    Vector { _handler: SPH4 },
    Vector { _handler: SPH5 },
    Vector { _handler: SPH6 },
    Vector { _handler: SPH7 },
    Vector { _handler: SPH8 },
    Vector { _handler: SPH9 },
    Vector { _handler: SPH10 },
    Vector { _handler: SPH11 },
    Vector { _handler: SPH12 },
    Vector { _handler: SPH13 },
    Vector { _handler: SPH14 },
    Vector { _handler: SPH15 },
    Vector { _reserved: 0 },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: GE2D },
    Vector { _handler: ROT },
    Vector { _handler: CISIF },
    Vector { _handler: SPI5 },
    Vector { _handler: DMAC3 },
    Vector { _handler: UART2 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI4 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DMAC1 },
];
///Enumeration of all the interrupts.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    ///1 - CRG interrupt
    CRG = 1,
    ///11 - UART1 interrupt
    UART1 = 11,
    ///16 - SPI3 interrupt
    SPI3 = 16,
    ///17 - I2C0 (SCU_I2C0) interrupt
    I2C0 = 17,
    ///18 - I2C1 (SCU_I2C1) interrupt
    I2C1 = 18,
    ///20 - GPIO external interrupt slot 0
    EXDEVICE_0 = 20,
    ///21 - GPIO external interrupt slot 1
    EXDEVICE_1 = 21,
    ///22 - GPIO external interrupt slot 2
    EXDEVICE_2 = 22,
    ///23 - GPIO external interrupt slot 3
    EXDEVICE_3 = 23,
    ///24 - GPIO external interrupt slot 4
    EXDEVICE_4 = 24,
    ///25 - GPIO external interrupt slot 5
    EXDEVICE_5 = 25,
    ///26 - GPIO external interrupt slot 6
    EXDEVICE_6 = 26,
    ///27 - GPIO external interrupt slot 7
    EXDEVICE_7 = 27,
    ///28 - GPIO external interrupt slot 8
    EXDEVICE_8 = 28,
    ///29 - GPIO external interrupt slot 9
    EXDEVICE_9 = 29,
    ///30 - GPIO external interrupt slot 10
    EXDEVICE_10 = 30,
    ///31 - GPIO external interrupt slot 11
    EXDEVICE_11 = 31,
    ///74 - SPI0 interrupt
    SPI0 = 74,
    ///78 - CPU FIFO transmit ready (PUSH FIFO not full)
    FIFO_TO = 78,
    ///79 - CPU FIFO message received (PULL FIFO not empty)
    FIFO_FROM = 79,
    ///80 - Hardware semaphore 0 released-to-reserver wake
    SPH0 = 80,
    ///81 - Hardware semaphore 1 released-to-reserver wake
    SPH1 = 81,
    ///82 - Hardware semaphore 2 released-to-reserver wake
    SPH2 = 82,
    ///83 - Hardware semaphore 3 released-to-reserver wake
    SPH3 = 83,
    ///84 - Hardware semaphore 4 released-to-reserver wake
    SPH4 = 84,
    ///85 - Hardware semaphore 5 released-to-reserver wake
    SPH5 = 85,
    ///86 - Hardware semaphore 6 released-to-reserver wake
    SPH6 = 86,
    ///87 - Hardware semaphore 7 released-to-reserver wake
    SPH7 = 87,
    ///88 - Hardware semaphore 8 released-to-reserver wake
    SPH8 = 88,
    ///89 - Hardware semaphore 9 released-to-reserver wake
    SPH9 = 89,
    ///90 - Hardware semaphore 10 released-to-reserver wake
    SPH10 = 90,
    ///91 - Hardware semaphore 11 released-to-reserver wake
    SPH11 = 91,
    ///92 - Hardware semaphore 12 released-to-reserver wake
    SPH12 = 92,
    ///93 - Hardware semaphore 13 released-to-reserver wake
    SPH13 = 93,
    ///94 - Hardware semaphore 14 released-to-reserver wake
    SPH14 = 94,
    ///95 - Hardware semaphore 15 released-to-reserver wake
    SPH15 = 95,
    ///97 - TIMER0 interrupt
    TIMER0 = 97,
    ///98 - TIMER1 interrupt
    TIMER1 = 98,
    ///106 - 2D interrupt
    GE2D = 106,
    ///107 - Rotation interrupt
    ROT = 107,
    ///108 - CISIF interrupt
    CISIF = 108,
    ///109 - SPI5 interrupt
    SPI5 = 109,
    ///110 - DMAC3 interrupt
    DMAC3 = 110,
    ///111 - UART2 interrupt
    UART2 = 111,
    ///113 - SPI4 interrupt
    SPI4 = 113,
    ///118 - DMAC1 interrupt
    DMAC1 = 118,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
///SRAM Control
pub type SmpRamCtrl = crate::Periph<smp_ram_ctrl::RegisterBlock, 0x0200_1000>;
impl core::fmt::Debug for SmpRamCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmpRamCtrl").finish()
    }
}
///SRAM Control
pub mod smp_ram_ctrl;
///Clock / Reset / Gating
pub type Crg = crate::Periph<crg::RegisterBlock, 0x0201_1000>;
impl core::fmt::Debug for Crg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crg").finish()
    }
}
///Clock / Reset / Gating
pub mod crg;
///Address Converter
pub type Addrconv = crate::Periph<addrconv::RegisterBlock, 0x0201_2000>;
impl core::fmt::Debug for Addrconv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Addrconv").finish()
    }
}
///Address Converter
pub mod addrconv;
///Hardware 2D Graphics Engine
pub type Ge2d = crate::Periph<ge2d::RegisterBlock, 0x0210_1000>;
impl core::fmt::Debug for Ge2d {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ge2d").finish()
    }
}
///Hardware 2D Graphics Engine
pub mod ge2d;
///Image rotation
pub type Rot = crate::Periph<rot::RegisterBlock, 0x0210_1400>;
impl core::fmt::Debug for Rot {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rot").finish()
    }
}
///Image rotation
pub mod rot;
///CPU FIFO Control
pub type CpuFifo = crate::Periph<cpu_fifo::RegisterBlock, 0x4600_c400>;
impl core::fmt::Debug for CpuFifo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CpuFifo").finish()
    }
}
///CPU FIFO Control
pub mod cpu_fifo;
///Hardware semaphores (16) for inter-CPU mutual exclusion
pub type Sph = crate::Periph<sph::RegisterBlock, 0x4600_c800>;
impl core::fmt::Debug for Sph {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sph").finish()
    }
}
///Hardware semaphores (16) for inter-CPU mutual exclusion
pub mod sph;
///ARM PrimeCell SP804 dual-input timer 0
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0xe004_3000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
///ARM PrimeCell SP804 dual-input timer 0
pub mod timer0;
///ARM PrimeCell SP804 dual-input timer 1
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0xe004_3020>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
///ARM PrimeCell SP804 dual-input timer 1
pub use self::timer0 as timer1;
///ARM PrimeCell SP805 watchdog timer
pub type Wdog = crate::Periph<wdog::RegisterBlock, 0xe004_4000>;
impl core::fmt::Debug for Wdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog").finish()
    }
}
///ARM PrimeCell SP805 watchdog timer
pub mod wdog;
///UART
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x041a_c000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
///UART
pub mod uart1;
///UART
pub type Uart2 = crate::Periph<uart2::RegisterBlock, 0x0210_3000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
///UART
pub mod uart2;
///DMA controller (ADMAC)
pub type Dmac1 = crate::Periph<dmac1::RegisterBlock, 0x0202_0000>;
impl core::fmt::Debug for Dmac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac1").finish()
    }
}
///DMA controller (ADMAC)
pub mod dmac1;
///DMA controller (IDMAC)
pub type Dmac3 = crate::Periph<dmac3::RegisterBlock, 0x0210_2000>;
impl core::fmt::Debug for Dmac3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac3").finish()
    }
}
///DMA controller (IDMAC)
pub mod dmac3;
///Synchronous Serial Port Controller (SPIM)
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x041a_a000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
///Synchronous Serial Port Controller (SPIM)
pub mod spi0;
///Synchronous Serial Port Controller (SCU SPI)
pub type Spi3 = crate::Periph<spi0::RegisterBlock, 0x0418_d000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
///Synchronous Serial Port Controller (SCU SPI)
pub use self::spi0 as spi3;
///DesignWare DW_apb_i2c master controller (SCU_I2C0 / sensor I2C bus)
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x0418_d400>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
///DesignWare DW_apb_i2c master controller (SCU_I2C0 / sensor I2C bus)
pub mod i2c0;
///DesignWare DW_apb_i2c master controller (SCU_I2C1)
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x0418_d800>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
///DesignWare DW_apb_i2c master controller (SCU_I2C1)
pub use self::i2c0 as i2c1;
///SCU ADC Interface — LPADC/HPADC control and per-channel FIFO read ports. CPU APB read of LPADC_FIFO(n) dequeues one sample from the hardware FIFO of LPADC channel n (no iSoP needed). UM §3.21.12.1; Mirror base 0x0418DC00.
pub type ScuAdcif = crate::Periph<scu_adcif::RegisterBlock, 0x0418_dc00>;
impl core::fmt::Debug for ScuAdcif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ScuAdcif").finish()
    }
}
///SCU ADC Interface — LPADC/HPADC control and per-channel FIFO read ports. CPU APB read of LPADC_FIFO(n) dequeues one sample from the hardware FIFO of LPADC channel n (no iSoP needed). UM §3.21.12.1; Mirror base 0x0418DC00.
pub mod scu_adcif;
///Synchronous Serial Port Controller (IMG SPI)
pub type Spi4 = crate::Periph<spi4::RegisterBlock, 0x0210_3400>;
impl core::fmt::Debug for Spi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi4").finish()
    }
}
///Synchronous Serial Port Controller (IMG SPI)
pub mod spi4;
///Synchronous Serial Port Controller (IMG WSPI)
pub type Spi5 = crate::Periph<spi4::RegisterBlock, 0x0210_3c00>;
impl core::fmt::Debug for Spi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi5").finish()
    }
}
///Synchronous Serial Port Controller (IMG WSPI)
pub use self::spi4 as spi5;
///Top-of-chip clock / PMU / oscillator / PLL controller
pub type Topreg = crate::Periph<topreg::RegisterBlock, 0x0410_0000>;
impl core::fmt::Debug for Topreg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Topreg").finish()
    }
}
///Top-of-chip clock / PMU / oscillator / PLL controller
pub mod topreg;
///APP / GNSS sub-domain clock and reset controller
pub type TopregSub = crate::Periph<topreg_sub::RegisterBlock, 0x0410_3000>;
impl core::fmt::Debug for TopregSub {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TopregSub").finish()
    }
}
///APP / GNSS sub-domain clock and reset controller
pub mod topreg_sub;
///Real-time clock 0 (always-on, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub type Rtc0 = crate::Periph<rtc0::RegisterBlock, 0x0410_8000>;
impl core::fmt::Debug for Rtc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0").finish()
    }
}
///Real-time clock 0 (always-on, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub mod rtc0;
///Real-time clock 1 (SYSIOP-gated, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub type Rtc1 = crate::Periph<rtc0::RegisterBlock, 0x0410_9000>;
impl core::fmt::Debug for Rtc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1").finish()
    }
}
///Real-time clock 1 (SYSIOP-gated, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub use self::rtc0 as rtc1;
///CMOS Image Sensor IF
pub type Cisif = crate::Periph<cisif::RegisterBlock, 0x0210_0000>;
impl core::fmt::Debug for Cisif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cisif").finish()
    }
}
///CMOS Image Sensor IF
pub mod cisif;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///SMP_RAM_CTRL
    pub smp_ram_ctrl: SmpRamCtrl,
    ///CRG
    pub crg: Crg,
    ///ADDRCONV
    pub addrconv: Addrconv,
    ///GE2D
    pub ge2d: Ge2d,
    ///ROT
    pub rot: Rot,
    ///CPU_FIFO
    pub cpu_fifo: CpuFifo,
    ///SPH
    pub sph: Sph,
    ///TIMER0
    pub timer0: Timer0,
    ///TIMER1
    pub timer1: Timer1,
    ///WDOG
    pub wdog: Wdog,
    ///UART1
    pub uart1: Uart1,
    ///UART2
    pub uart2: Uart2,
    ///DMAC1
    pub dmac1: Dmac1,
    ///DMAC3
    pub dmac3: Dmac3,
    ///SPI0
    pub spi0: Spi0,
    ///SPI3
    pub spi3: Spi3,
    ///I2C0
    pub i2c0: I2c0,
    ///I2C1
    pub i2c1: I2c1,
    ///SCU_ADCIF
    pub scu_adcif: ScuAdcif,
    ///SPI4
    pub spi4: Spi4,
    ///SPI5
    pub spi5: Spi5,
    ///TOPREG
    pub topreg: Topreg,
    ///TOPREG_SUB
    pub topreg_sub: TopregSub,
    ///RTC0
    pub rtc0: Rtc0,
    ///RTC1
    pub rtc1: Rtc1,
    ///CISIF
    pub cisif: Cisif,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            smp_ram_ctrl: unsafe { SmpRamCtrl::steal() },
            crg: unsafe { Crg::steal() },
            addrconv: unsafe { Addrconv::steal() },
            ge2d: unsafe { Ge2d::steal() },
            rot: unsafe { Rot::steal() },
            cpu_fifo: unsafe { CpuFifo::steal() },
            sph: unsafe { Sph::steal() },
            timer0: unsafe { Timer0::steal() },
            timer1: unsafe { Timer1::steal() },
            wdog: unsafe { Wdog::steal() },
            uart1: unsafe { Uart1::steal() },
            uart2: unsafe { Uart2::steal() },
            dmac1: unsafe { Dmac1::steal() },
            dmac3: unsafe { Dmac3::steal() },
            spi0: unsafe { Spi0::steal() },
            spi3: unsafe { Spi3::steal() },
            i2c0: unsafe { I2c0::steal() },
            i2c1: unsafe { I2c1::steal() },
            scu_adcif: unsafe { ScuAdcif::steal() },
            spi4: unsafe { Spi4::steal() },
            spi5: unsafe { Spi5::steal() },
            topreg: unsafe { Topreg::steal() },
            topreg_sub: unsafe { TopregSub::steal() },
            rtc0: unsafe { Rtc0::steal() },
            rtc1: unsafe { Rtc1::steal() },
            cisif: unsafe { Cisif::steal() },
        }
    }
}
