#![doc = "Peripheral access API for CXD5602 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn CRG();
    fn UART1();
    fn SPI3();
    fn SPI0();
    fn _2D();
    fn ROT();
    fn CISIF();
    fn SPI5();
    fn DMAC3();
    fn UART2();
    fn SPI4();
    fn DMAC1();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 135] = [
    Vector { _reserved: 0 },
    Vector { _handler: CRG },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: _2D },
    Vector { _handler: ROT },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: CISIF },
    Vector { _handler: SPI5 },
    Vector { _handler: DMAC3 },
    Vector { _handler: UART2 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI4 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DMAC1 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "1 - CRG interrupt"]
    CRG = 1,
    #[doc = "27 - UART1 interrupt"]
    UART1 = 27,
    #[doc = "32 - SPI3 interrupt"]
    SPI3 = 32,
    #[doc = "90 - SPI0 interrupt"]
    SPI0 = 90,
    #[doc = "106 - 2D interrupt"]
    _2D = 106,
    #[doc = "107 - Rotation interrupt"]
    ROT = 107,
    #[doc = "124 - CISIF interrupt"]
    CISIF = 124,
    #[doc = "125 - SPI5 interrupt"]
    SPI5 = 125,
    #[doc = "126 - DMAC3 interrupt"]
    DMAC3 = 126,
    #[doc = "127 - UART2 interrupt"]
    UART2 = 127,
    #[doc = "129 - SPI4 interrupt"]
    SPI4 = 129,
    #[doc = "134 - DMAC1 interrupt"]
    DMAC1 = 134,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "SRAM Control"]
pub type SmpRamCtrl = crate::Periph<smp_ram_ctrl::RegisterBlock, 0x0200_1000>;
impl core::fmt::Debug for SmpRamCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmpRamCtrl").finish()
    }
}
#[doc = "SRAM Control"]
pub mod smp_ram_ctrl;
#[doc = "Clock / Reset / Gating"]
pub type Crg = crate::Periph<crg::RegisterBlock, 0x0201_1000>;
impl core::fmt::Debug for Crg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crg").finish()
    }
}
#[doc = "Clock / Reset / Gating"]
pub mod crg;
#[doc = "Address Converter"]
pub type Addrconv = crate::Periph<addrconv::RegisterBlock, 0x0201_2000>;
impl core::fmt::Debug for Addrconv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Addrconv").finish()
    }
}
#[doc = "Address Converter"]
pub mod addrconv;
#[doc = "Hardware 2D Graphics Engine"]
pub type Ge2d = crate::Periph<ge2d::RegisterBlock, 0x0210_1000>;
impl core::fmt::Debug for Ge2d {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ge2d").finish()
    }
}
#[doc = "Hardware 2D Graphics Engine"]
pub mod ge2d;
#[doc = "Image rotation"]
pub type Rot = crate::Periph<rot::RegisterBlock, 0x0210_1400>;
impl core::fmt::Debug for Rot {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rot").finish()
    }
}
#[doc = "Image rotation"]
pub mod rot;
#[doc = "CPU FIFO Control"]
pub type CpuFifo = crate::Periph<cpu_fifo::RegisterBlock, 0x4600_c400>;
impl core::fmt::Debug for CpuFifo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CpuFifo").finish()
    }
}
#[doc = "CPU FIFO Control"]
pub mod cpu_fifo;
#[doc = "UART"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x041a_c000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART"]
pub mod uart1;
#[doc = "UART"]
pub type Uart2 = crate::Periph<uart2::RegisterBlock, 0x0210_3000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "UART"]
pub mod uart2;
#[doc = "DMA controller (ADMAC)"]
pub type Dmac1 = crate::Periph<dmac1::RegisterBlock, 0x0202_0000>;
impl core::fmt::Debug for Dmac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac1").finish()
    }
}
#[doc = "DMA controller (ADMAC)"]
pub mod dmac1;
#[doc = "DMA controller (IDMAC)"]
pub type Dmac3 = crate::Periph<dmac3::RegisterBlock, 0x0210_2000>;
impl core::fmt::Debug for Dmac3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac3").finish()
    }
}
#[doc = "DMA controller (IDMAC)"]
pub mod dmac3;
#[doc = "Synchronous Serial Port Controller (SPIM)"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x041a_a000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Synchronous Serial Port Controller (SPIM)"]
pub mod spi0;
#[doc = "Synchronous Serial Port Controller (SCU SPI)"]
pub type Spi3 = crate::Periph<spi0::RegisterBlock, 0x0418_d000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "Synchronous Serial Port Controller (SCU SPI)"]
pub use self::spi0 as spi3;
#[doc = "Synchronous Serial Port Controller (IMG SPI)"]
pub type Spi4 = crate::Periph<spi4::RegisterBlock, 0x0210_3400>;
impl core::fmt::Debug for Spi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi4").finish()
    }
}
#[doc = "Synchronous Serial Port Controller (IMG SPI)"]
pub mod spi4;
#[doc = "Synchronous Serial Port Controller (IMG WSPI)"]
pub type Spi5 = crate::Periph<spi4::RegisterBlock, 0x0210_3c00>;
impl core::fmt::Debug for Spi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi5").finish()
    }
}
#[doc = "Synchronous Serial Port Controller (IMG WSPI)"]
pub use self::spi4 as spi5;
#[doc = "GPIO Port 0 — GP_* output-enable/data registers"]
pub type Gpio0 = crate::Periph<gpio0::RegisterBlock, 0x0410_2000>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
#[doc = "GPIO Port 0 — GP_* output-enable/data registers"]
pub mod gpio0;
#[doc = "CMOS Image Sensor IF"]
pub type Cisif = crate::Periph<cisif::RegisterBlock, 0x0210_0000>;
impl core::fmt::Debug for Cisif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cisif").finish()
    }
}
#[doc = "CMOS Image Sensor IF"]
pub mod cisif;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SMP_RAM_CTRL"]
    pub smp_ram_ctrl: SmpRamCtrl,
    #[doc = "CRG"]
    pub crg: Crg,
    #[doc = "ADDRCONV"]
    pub addrconv: Addrconv,
    #[doc = "GE2D"]
    pub ge2d: Ge2d,
    #[doc = "ROT"]
    pub rot: Rot,
    #[doc = "CPU_FIFO"]
    pub cpu_fifo: CpuFifo,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "DMAC1"]
    pub dmac1: Dmac1,
    #[doc = "DMAC3"]
    pub dmac3: Dmac3,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SPI4"]
    pub spi4: Spi4,
    #[doc = "SPI5"]
    pub spi5: Spi5,
    #[doc = "GPIO0"]
    pub gpio0: Gpio0,
    #[doc = "CISIF"]
    pub cisif: Cisif,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe {
            DEVICE_PERIPHERALS = true;
            Peripherals {
                smp_ram_ctrl: SmpRamCtrl::steal(),
                crg: Crg::steal(),
                addrconv: Addrconv::steal(),
                ge2d: Ge2d::steal(),
                rot: Rot::steal(),
                cpu_fifo: CpuFifo::steal(),
                uart1: Uart1::steal(),
                uart2: Uart2::steal(),
                dmac1: Dmac1::steal(),
                dmac3: Dmac3::steal(),
                spi0: Spi0::steal(),
                spi3: Spi3::steal(),
                spi4: Spi4::steal(),
                spi5: Spi5::steal(),
                gpio0: Gpio0::steal(),
                cisif: Cisif::steal(),
            }
        }
    }
}
