/*!Peripheral access API for CXD5602 microcontrollers (generated using svd2rust v0.37.1 ( ))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
///Common register and bit access and modify traits
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn CRG();
    fn UART1();
    fn SPI3();
    fn SPI0();
    fn _2D();
    fn ROT();
    fn CISIF();
    fn SPI5();
    fn DMAC3();
    fn UART2();
    fn SPI4();
    fn DMAC1();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 135] = [
    Vector { _reserved: 0 },
    Vector { _handler: CRG },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: _2D },
    Vector { _handler: ROT },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: CISIF },
    Vector { _handler: SPI5 },
    Vector { _handler: DMAC3 },
    Vector { _handler: UART2 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI4 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DMAC1 },
];
///Enumeration of all the interrupts.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    ///1 - CRG interrupt
    CRG = 1,
    ///27 - UART1 interrupt
    UART1 = 27,
    ///32 - SPI3 interrupt
    SPI3 = 32,
    ///90 - SPI0 interrupt
    SPI0 = 90,
    ///106 - 2D interrupt
    _2D = 106,
    ///107 - Rotation interrupt
    ROT = 107,
    ///124 - CISIF interrupt
    CISIF = 124,
    ///125 - SPI5 interrupt
    SPI5 = 125,
    ///126 - DMAC3 interrupt
    DMAC3 = 126,
    ///127 - UART2 interrupt
    UART2 = 127,
    ///129 - SPI4 interrupt
    SPI4 = 129,
    ///134 - DMAC1 interrupt
    DMAC1 = 134,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
///SRAM Control
pub type SmpRamCtrl = crate::Periph<smp_ram_ctrl::RegisterBlock, 0x0200_1000>;
impl core::fmt::Debug for SmpRamCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmpRamCtrl").finish()
    }
}
///SRAM Control
pub mod smp_ram_ctrl;
///Clock / Reset / Gating
pub type Crg = crate::Periph<crg::RegisterBlock, 0x0201_1000>;
impl core::fmt::Debug for Crg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crg").finish()
    }
}
///Clock / Reset / Gating
pub mod crg;
///Address Converter
pub type Addrconv = crate::Periph<addrconv::RegisterBlock, 0x0201_2000>;
impl core::fmt::Debug for Addrconv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Addrconv").finish()
    }
}
///Address Converter
pub mod addrconv;
///Hardware 2D Graphics Engine
pub type Ge2d = crate::Periph<ge2d::RegisterBlock, 0x0210_1000>;
impl core::fmt::Debug for Ge2d {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ge2d").finish()
    }
}
///Hardware 2D Graphics Engine
pub mod ge2d;
///Image rotation
pub type Rot = crate::Periph<rot::RegisterBlock, 0x0210_1400>;
impl core::fmt::Debug for Rot {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rot").finish()
    }
}
///Image rotation
pub mod rot;
///CPU FIFO Control
pub type CpuFifo = crate::Periph<cpu_fifo::RegisterBlock, 0x4600_c400>;
impl core::fmt::Debug for CpuFifo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CpuFifo").finish()
    }
}
///CPU FIFO Control
pub mod cpu_fifo;
///ARM PrimeCell SP804 dual-input timer 0
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0xe004_3000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
///ARM PrimeCell SP804 dual-input timer 0
pub mod timer0;
///ARM PrimeCell SP804 dual-input timer 1
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0xe004_3020>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
///ARM PrimeCell SP804 dual-input timer 1
pub use self::timer0 as timer1;
///ARM PrimeCell SP805 watchdog timer
pub type Wdog = crate::Periph<wdog::RegisterBlock, 0xe004_4000>;
impl core::fmt::Debug for Wdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog").finish()
    }
}
///ARM PrimeCell SP805 watchdog timer
pub mod wdog;
///UART
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x041a_c000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
///UART
pub mod uart1;
///UART
pub type Uart2 = crate::Periph<uart2::RegisterBlock, 0x0210_3000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
///UART
pub mod uart2;
///DMA controller (ADMAC)
pub type Dmac1 = crate::Periph<dmac1::RegisterBlock, 0x0202_0000>;
impl core::fmt::Debug for Dmac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac1").finish()
    }
}
///DMA controller (ADMAC)
pub mod dmac1;
///DMA controller (IDMAC)
pub type Dmac3 = crate::Periph<dmac3::RegisterBlock, 0x0210_2000>;
impl core::fmt::Debug for Dmac3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac3").finish()
    }
}
///DMA controller (IDMAC)
pub mod dmac3;
///Synchronous Serial Port Controller (SPIM)
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x041a_a000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
///Synchronous Serial Port Controller (SPIM)
pub mod spi0;
///Synchronous Serial Port Controller (SCU SPI)
pub type Spi3 = crate::Periph<spi0::RegisterBlock, 0x0418_d000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
///Synchronous Serial Port Controller (SCU SPI)
pub use self::spi0 as spi3;
///Synchronous Serial Port Controller (IMG SPI)
pub type Spi4 = crate::Periph<spi4::RegisterBlock, 0x0210_3400>;
impl core::fmt::Debug for Spi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi4").finish()
    }
}
///Synchronous Serial Port Controller (IMG SPI)
pub mod spi4;
///Synchronous Serial Port Controller (IMG WSPI)
pub type Spi5 = crate::Periph<spi4::RegisterBlock, 0x0210_3c00>;
impl core::fmt::Debug for Spi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi5").finish()
    }
}
///Synchronous Serial Port Controller (IMG WSPI)
pub use self::spi4 as spi5;
///Top-of-chip clock / PMU / oscillator / PLL controller
pub type Topreg = crate::Periph<topreg::RegisterBlock, 0x0410_0000>;
impl core::fmt::Debug for Topreg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Topreg").finish()
    }
}
///Top-of-chip clock / PMU / oscillator / PLL controller
pub mod topreg;
///APP / GNSS sub-domain clock and reset controller
pub type TopregSub = crate::Periph<topreg_sub::RegisterBlock, 0x0410_3000>;
impl core::fmt::Debug for TopregSub {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TopregSub").finish()
    }
}
///APP / GNSS sub-domain clock and reset controller
pub mod topreg_sub;
///Real-time clock 0 (always-on, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub type Rtc0 = crate::Periph<rtc0::RegisterBlock, 0x0410_8000>;
impl core::fmt::Debug for Rtc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0").finish()
    }
}
///Real-time clock 0 (always-on, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub mod rtc0;
///Real-time clock 1 (SYSIOP-gated, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub type Rtc1 = crate::Periph<rtc0::RegisterBlock, 0x0410_9000>;
impl core::fmt::Debug for Rtc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1").finish()
    }
}
///Real-time clock 1 (SYSIOP-gated, 32.768 kHz, 47-bit dual counter, 3 alarms)
pub use self::rtc0 as rtc1;
///CMOS Image Sensor IF
pub type Cisif = crate::Periph<cisif::RegisterBlock, 0x0210_0000>;
impl core::fmt::Debug for Cisif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cisif").finish()
    }
}
///CMOS Image Sensor IF
pub mod cisif;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///SMP_RAM_CTRL
    pub smp_ram_ctrl: SmpRamCtrl,
    ///CRG
    pub crg: Crg,
    ///ADDRCONV
    pub addrconv: Addrconv,
    ///GE2D
    pub ge2d: Ge2d,
    ///ROT
    pub rot: Rot,
    ///CPU_FIFO
    pub cpu_fifo: CpuFifo,
    ///TIMER0
    pub timer0: Timer0,
    ///TIMER1
    pub timer1: Timer1,
    ///WDOG
    pub wdog: Wdog,
    ///UART1
    pub uart1: Uart1,
    ///UART2
    pub uart2: Uart2,
    ///DMAC1
    pub dmac1: Dmac1,
    ///DMAC3
    pub dmac3: Dmac3,
    ///SPI0
    pub spi0: Spi0,
    ///SPI3
    pub spi3: Spi3,
    ///SPI4
    pub spi4: Spi4,
    ///SPI5
    pub spi5: Spi5,
    ///TOPREG
    pub topreg: Topreg,
    ///TOPREG_SUB
    pub topreg_sub: TopregSub,
    ///RTC0
    pub rtc0: Rtc0,
    ///RTC1
    pub rtc1: Rtc1,
    ///CISIF
    pub cisif: Cisif,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            smp_ram_ctrl: SmpRamCtrl::steal(),
            crg: Crg::steal(),
            addrconv: Addrconv::steal(),
            ge2d: Ge2d::steal(),
            rot: Rot::steal(),
            cpu_fifo: CpuFifo::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            wdog: Wdog::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
            dmac1: Dmac1::steal(),
            dmac3: Dmac3::steal(),
            spi0: Spi0::steal(),
            spi3: Spi3::steal(),
            spi4: Spi4::steal(),
            spi5: Spi5::steal(),
            topreg: Topreg::steal(),
            topreg_sub: TopregSub::steal(),
            rtc0: Rtc0::steal(),
            rtc1: Rtc1::steal(),
            cisif: Cisif::steal(),
        }
    }
}
