//! CXD5247 audio analog companion (ACA) control via Far API.
//!
//! On the Spresense main board the audio master clock (24.576 MHz) that the
//! CXD5602 audio block needs is generated by the external **CXD5247** companion
//! chip. The companion is brought up by asking the SYSIOP loader firmware to run
//! `fw_as_acacontrol(cmd, param)` — see [`crate::farapi`]. Without this the
//! audio MCLK never runs and any access to the audio block's AHB space stalls
//! the bus (User Manual §3.15.6.16).
//!
//! This module wraps `fw_as_acacontrol`. Today it exposes [`check_id`] — the
//! make-or-break probe that the loader firmware actually answers ACA calls —
//! and the generic [`acacontrol`] entry the rest of the bring-up will build on.
//!
//! Command codes and parameter values mirror `nuttx/.../cxd5247.c` and
//! `boards/.../audio/cxd56_audio_aca.c`.

use core::sync::atomic::{Ordering, compiler_fence};

use crate::farapi::{self, FarapiError};

/// Module index of the ACA module in the SYSIOP firmware module table — the
/// position of `_modulelist_aca` in `cxd56_farapistub.S` (power_mgr=0,
/// flash_mgr=1, rtc_mgr=2, gnss_pwr=3, **aca=4**).
const ACA_MODID: i32 = 4;

/// Far API function index for `fw_as_acacontrol`. The NuttX asm stub derives it
/// from its own PC as `(&fw_as_acacontrol + 4) - &api_table_base`; for the ACA
/// module the function sits at the table base, so the value is 4
/// (`cxd56_farapistub.S:573`). [`check_id`] validates this on hardware.
const ACA_API_ID: i32 = 4;

/// ACA control commands — the `type` argument of `fw_as_acacontrol`
/// (`cxd5247.c:36`).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u32)]
pub enum AcaCmd {
    /// Probe the companion is present and responding.
    CheckId = 0,
    /// Power on the common (clock/oscillator) block.
    PowerOnCommon = 1,
    /// Configure the serializer/deserializer routing.
    SetSerdes = 4,
    /// Configure the S-master (PWM) clocking.
    SetSmaster = 5,
    /// Power off the common block.
    PowerOffCommon = 6,
}

/// Error from an ACA control call.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum AcaError {
    /// The Far API transport timed out — the loader firmware did not answer,
    /// typically because it does not expose the ACA module.
    Farapi,
    /// The ACA firmware ran but returned a non-zero status code.
    Status(u32),
}

impl From<FarapiError> for AcaError {
    fn from(_: FarapiError) -> Self {
        AcaError::Farapi
    }
}

/// Issue one `fw_as_acacontrol(cmd, param)`.
///
/// `param` is the raw second argument: `0`, or the address of a parameter
/// struct cast to `u32`. The struct must outlive the call (the SYSIOP reads it
/// during the blocking call). Returns the firmware status (`0` = OK).
pub fn acacontrol(cmd: AcaCmd, param: u32) -> Result<(), AcaError> {
    // arg mirrors the r0-r3 the NuttX asm stub pushes: [type, param, _, _].
    // The firmware reads arg[0]/arg[1] and writes its return value to arg[0].
    let mut arg = [cmd as u32, param, 0, 0];
    farapi::call(ACA_MODID, ACA_API_ID, &mut arg, farapi::DEFAULT_POLL_BUDGET)?;
    match arg[0] {
        0 => Ok(()),
        status => Err(AcaError::Status(status)),
    }
}

/// PMIC channel for the CXD5247 analog audio supply — `POWER_AUDIO_AVDD =
/// PMIC_GPO(1)` (`board.h`).
const AVDD_GPO_CH: u8 = 1 << 1;
/// PMIC channel for the CXD5247 digital audio supply — `POWER_AUDIO_DVDD =
/// PMIC_LSW(2)` (`board.h`).
const DVDD_LSW_CH: u8 = 1 << 2;

/// Route the `MCLK` pad to its master-clock function so the CXD5247's
/// 24.576 MHz master clock reaches the CXD5602 audio block. `PIN_MCLK = 101`;
/// until this pad is muxed the clock never enters the block and every audio
/// register access stalls the AHB. Mirrors `board_audio_initialize`'s
/// `CXD56_PIN_CONFIGS(PINCONFS_MCLK)` = `PINCONF(PIN_MCLK, mode1, input, 2mA,
/// float)`. Must run before any audio register access.
pub fn mclk_pin_config() {
    let t = crate::regs::topreg();
    // IO-cell: 2 mA drive (LOWEMI), float (PDN+PUN off), input buffer enabled.
    t.io_mclk().write(|w| {
        w.lowemi()
            .set_bit()
            .pdn()
            .set_bit()
            .pun()
            .set_bit()
            .enzi()
            .set_bit()
    });
    // Function select: MCLK pad = Func1 (master clock). Shares IOCAPP_IOMD with
    // the i2s0 field, so modify to preserve it (GROUP_MCLK = bits[23:22]).
    t.iocapp_iomd().modify(|_, w| unsafe { w.mclk().bits(1) });
}

/// Power on the CXD5247 audio companion.
///
/// Mirrors `board_aca_power_control(CXD5247_AVDD | CXD5247_DVDD, true)`
/// (`cxd56_audio.c:180`): configure the `XRST` GPIO, assert reset low, bring up
/// AVDD (PMIC GPO ch1) then DVDD (PMIC LSW ch2), and release reset high. The
/// reset cycle with the rails up is what makes the companion's audio/digital
/// section answer on its I2C interface (otherwise [`check_id`] sees the
/// firmware's `PD_I2c` read error). The caller should allow a short settle
/// before [`check_id`].
pub fn cxd5247_power_on() -> Result<(), AcaError> {
    // XRST = GP_SPI3_CS2_X. DIR is active-low output-enable (set = high-Z input,
    // clear = drive); OUT is the level.
    let xrst = crate::regs::topreg().gp_spi3_cs2_x();
    xrst.write(|w| w.dir().set_bit().out().clear_bit()); // config: output disabled
    xrst.write(|w| w.dir().clear_bit().out().clear_bit()); // assert reset: drive low
    crate::pmic::set_gpo(AVDD_GPO_CH, true)?;
    crate::pmic::set_loadswitch(DVDD_LSW_CH, true)?;
    xrst.write(|w| w.dir().clear_bit().out().set_bit()); // release reset: drive high
    Ok(())
}

/// Probe the companion: `fw_as_acacontrol(CHECK_ID, 0)`.
///
/// This is the gate for the whole CXD5247 audio bring-up: it succeeds only when
/// the loader firmware on the board exposes the ACA module and the companion
/// answers. If it returns [`AcaError::Farapi`] (timeout), the SYSIOP firmware
/// does not provide ACA and a different MCLK source is required.
pub fn check_id() -> Result<(), AcaError> {
    acacontrol(AcaCmd::CheckId, 0)
}

/// `as_aca_pulco_param_t` (`cxd56_audio_aca.c:262`) — argument of
/// `POWER_ON_COMMON`. Field values for the Spresense main-board default config
/// (24.576 MHz, normal resolution, no analog mics, weakest drive).
#[repr(C)]
struct PulcoParam {
    osc_mode: u32,
    mic_dev: u32,
    gpo_ds: u32,
    ad_data_ds: u32,
    dmic_clk_ds: u32,
    mclk_ds: u32,
}

/// `as_ser_des_param_t` (`cxd56_audio_aca.c:309`) — argument of `SET_SERDES`.
/// `sel_ch` is the 8-channel mic-routing array (`CXD56_AUDIO_MIC_CH_MAX = 8`),
/// all `FIX0` here since no mics are wired for the I2S loopback.
#[repr(C)]
struct SerDesParam {
    ser_mode: u32,
    ser_fs: u32,
    sel_ch: [u32; 8],
}

// as_aca_pulco_osc_mode_id_t: 24.576 MHz, normal resolution.
const OSC_24_576MHZ: u32 = 1;
// as_aca_pulco_mic_device_id_t: no analog mics -> DMIC (get_mic_dev default).
const MIC_DEV_DMIC: u32 = 2;
// as_aca_pulco_io_ds_id_t: weakest drive (board default for every *_DS).
const IO_DS_WEAKEST: u32 = 1;
// as_aca_pulco_ser_mode_id_t / _fs_id_t board defaults (non-128fs path).
const SER_MODE_8CH: u32 = 1;
const SER_FS_64: u32 = 2;

/// Power on the CXD5247 common block — `fw_as_acacontrol(POWER_ON_COMMON, …)`.
///
/// This starts the companion's 24.576 MHz oscillator, i.e. the audio **MCLK**
/// the CXD5602 audio block needs before its registers are accessible. Mirrors
/// `cxd56_audio_aca_poweron`'s `POWER_ON_COMMON` step with `get_pwon_param`'s
/// default-config values.
pub fn power_on_common() -> Result<(), AcaError> {
    let p = PulcoParam {
        osc_mode: OSC_24_576MHZ,
        mic_dev: MIC_DEV_DMIC,
        gpo_ds: IO_DS_WEAKEST,
        ad_data_ds: IO_DS_WEAKEST,
        dmic_clk_ds: IO_DS_WEAKEST,
        mclk_ds: IO_DS_WEAKEST,
    };
    compiler_fence(Ordering::SeqCst);
    acacontrol(AcaCmd::PowerOnCommon, (&p as *const PulcoParam) as u32)
}

/// Configure the CXD5247 serializer — `fw_as_acacontrol(SET_SERDES, …)`.
///
/// This sets up the **microphone** serializer and is **not** part of the I2S0
/// TX/RX path. It is provided for completeness; the I2S loopback does not call
/// it. Note: with no mics wired (all channels `FIX0`) the loader firmware
/// asserts (`aca_drv_sub_func.c:823`), so only call it with a valid mic config.
pub fn set_serdes() -> Result<(), AcaError> {
    let p = SerDesParam {
        ser_mode: SER_MODE_8CH,
        ser_fs: SER_FS_64,
        sel_ch: [0; 8],
    };
    compiler_fence(Ordering::SeqCst);
    acacontrol(AcaCmd::SetSerdes, (&p as *const SerDesParam) as u32)
}

/// Full companion power-on after the supplies/reset are up
/// ([`cxd5247_power_on`]): probe the companion, then start the MCLK oscillator.
///
/// Mirrors the I2S-relevant part of `cxd56_audio_aca_poweron`. The `SET_SERDES`
/// step is intentionally omitted — it configures the mic serializer (not used
/// by I2S0) and asserts in firmware without a valid mic config; see
/// [`set_serdes`].
pub fn aca_poweron() -> Result<(), AcaError> {
    check_id()?;
    power_on_common()?;
    Ok(())
}
